name: causal graphs
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: causal graphs
        run: |
          # work
          cat data/outputs/output.txt >> report.md
          cml publish data/images/features_correlation.png --md >> report.md
          cml publish data/images/ground_truth.png --md >> report.md
          cml publish data/images/importance_original.png --md >> report.md
          cml send-comment report.md